<?php

class Person
{
    protected $name;
    protected $age;


    function __construct($name, $idade)
    {
        $this->name = $name;
        $this->age = $idade;
    }

    public function info()
    {
        return "O meu nome é $this->name, tenho $this->age anos";
    }
}


$lucca = new Person("Lucca", 14);
echo $lucca->info();

class User extends Person
{
    private $BaseEmail;
    private $basePassword;

    function __construct($name, $idade, $BaseEmail, $basePassword)
    {
        parent::__construct($name, $idade);
        $this->BaseEmail = $BaseEmail;
        $this->basePassword = $basePassword;
    }

    public function login($email,$password)
    {
        $check1 = $this->BaseEmail == $email;
        $check2 = $this->basePassword == $password;
        return ($check1 and $check2) ? "Acesso permitido" : "Acesso Não autorizado";


    }

    public function info()
    {

        # pegando os dados da classe pai e retornando com os modificadores
        return "Email: $this->BaseEmail Senha: $this->basePassword | " . parent::info(); // TODO: Change the autogenerated stub
    }
}

$carlos = new User("Carlos", 30, "carlos123@gamil.com", "15288963");
echo "\n";
echo $carlos->login("carlos123@gamil.com", "15288963");
echo "\n". $carlos->info();
